language: haskell
install:
  - npm install -g elm
  - elm-package install -y
  - console_version=$(node -pe 'JSON.parse(process.argv[1])["laszlopandy/elm-console"]' "$(cat elm-stuff/exact-dependencies.json)")
before_script: 
  - elm-make --yes --output raw-test.js test/TestRunner.elm
  - bash elm-stuff/packages/laszlopandy/elm-console/$console_version/elm-io.sh raw-test.js test.js
script: node test.js
