language: node_js
node_js:
  - "5"
install:
  - npm install -g elm
  - npm install -g elm-test
  - elm-package install -y
  - pushd test && elm-package install -y
  - elm-make TestRunner.elm --output test.js
  - popd
script:
  # - cd test && elm-test TestRunner.elm
  - node test/test.js
